# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build repo.json

on:
  push:
    branches: [ "main" ]
    paths:
      - 'repo/**'
      - 'build/build.js'
      - 'workflows/**'
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: node ./build/build.js
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: update repo.json
